# Generated by Django 6.0.4 on 2026-05-10 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_note_semester_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('DBMS', 'DBMS'), ('OS', 'Operating System'), ('CN', 'Computer Network'), ('Python', 'Python'), ('Java', 'Java'), ('AI', 'Artificial Intelligence')], max_length=100),
        ),
    ]
