# Generated by Django 6.0.4 on 2026-05-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
